### ISSUE TITLE
GitHub formatting?

### ISSUE THREAD

**Issue by wmayner** [ryanpcmcquen/workflowyCodeFormatter#7]
Thank you for making this extension! 😄 

It would be awesome if there was a way to use the `GitHub code style` (no visible backticks, darker background, smaller font size).

**Comment by ryanpcmcquen** [comment]
I _love_ GitHub's markdown style, however, it would be tricky to reproduce that in my extension for a few reasons:
1. There is currently no custom CSS with the extension, adding it would mean more complexity for the codebase.
2. These style changes would also need to take into account the different themes offered by WorkFlowy (which I cannot test all of because I don't have a premium account).

**Comment by wmayner** [comment]
I see, that makes sense. Thanks!
